service: lambda-step-func-demo

plugins:
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  stage: dev

functions:
  add:
    handler: functions/add.handler
    timeout: 3

  subtract:
    handler: functions/subtract.handler
    timeout: 3

  double:
    handler: functions/double.handler
    timeout: 3

stepFunctions:
  stateMachines:
    LambdaStepFuncDemo:    
      name: LambdaStepFunctionDemo      
      definition:
        Comment: "Simple demo of AWS Lambda and AWS Step Functions working together"
        StartAt: choose
        States:
          choose:
            Type: Choice
            Default: add
            Choices:
              - And: 
                  - Variable: $.x
                    NumericGreaterThanEquals: 42
                  - Variable: $.y
                    NumericLessThan: 42
                Next: subtract
          add:
            Type: Task
            Resource: 
              Fn::GetAtt: [add, Arn]
            Next: double
            ResultPath: $.n
          subtract:
            Type: Task
            Resource: 
              Fn::GetAtt: [subtract, Arn]
            Next: double
            ResultPath: $.n
          double:
            Type: Task
            Resource: 
              Fn::GetAtt: [double, Arn]              
            InputPath: $.n
            TimeoutSeconds: 1
            Retry: 
              - ErrorEquals:
                  - States.Timeout
                IntervalSeconds: 1
                BackoffRate: 2.0
                MaxAttempts: 2
            Catch: 
              - ErrorEquals:
                  - NumberIsTooBig
                ResultPath: $.error
                Next: numberIsTooBig
            End: true
          numberIsTooBig:
            Type: Fail
      # events:
      #   - http:
      #       path: /
      #       method: POST
      # alarms:
      #   topics:
      #     ok: arn:aws:sns:us-east-1:1234567890:NotifyMe
      #     alarm: arn:aws:sns:us-east-1:1234567890:NotifyMe
      #     insufficientData: arn:aws:sns:us-east-1:1234567890:NotifyMe
      #   metrics:
      #     - executionsTimeOut
      #     - executionsFailed
      #     - executionsAborted
      #     - executionThrottled
      # notifications:
      #   FAILED:
      #     - sqs: SQS_TOPIC_ARN